--- @type LazyPluginSpec
return {
    -- {
    --     'nvim-neorg/neorg',
    --     run = ':Neorg sync-parsers',
    --     version = '*',
    --     dependencies = {
    --         {
    --             'nvim-treesitter/nvim-treesitter',
    --         },
    --     },
    --     config = function()
    -- require('neorg').setup {
    --     load = {
    --         ["core.defaults"] = {},
    --         ["core.concealer"] = {},
    --     },
    -- }
    --     end,
    -- },
}
